### ISSUE TITLE
More helpful information when initializing

### ISSUE THREAD

**Issue by aaronyuai** [crynux-ai/crynux-node#206]
Initialization takes a long time, but with 0 helpful information.
We should tell users:
* Download progress
* Inference progress

**Comment by Shirazkp** [comment]
almost two hours 

System is initializing. This may take a while, please be patient...

**Comment by Proskhmer08** [comment]
I think if we can get additional stat in the Wallet section that would be helpful. Information on rate of CNX accrual, price per CNX would be good. Smaller font should be good. 

<img width="622" alt="Screenshot 2024-05-26 at 10 04 39 AM" src="https://github.com/crynux-ai/crynux-node/assets/35155781/ac3fa633-0d86-42a4-a96b-6729b0744246">
