### ISSUE TITLE
specific message for prefetch errors

### ISSUE THREAD

**Issue by lukewwww** [crynux-ai/crynux-node#221]
print logs of prefetch & init task to the log file

**Comment by Proskhmer08** [comment]
Can we also add a slashing event in the log to specifically record a "slashed" event has occurred in the log?

**Comment by lukewwww** [comment]
> Can we also add a slashing event in the log to specifically record a "slashed" event has occurred in the log?

#197

**Comment by Tacoz7183** [comment]
Getting this error on my mac

**Comment by lukewwww** [comment]
> Getting this error on my mac

This error is usually due to network issues, specifically connection to the Huggingface, you may try to use a proxy
