### ISSUE TITLE
WebUI Network Error: Cannot Get Account Info from Node

### ISSUE THREAD

**Issue by theguystudio1** [crynux-ai/crynux-node#261]
# Problem Description

A network error occurs When retrieving account information from the node. The system repeatedly displays the message: "Cannot get account info from node due to network error, retrying..."

---

## Error Log

[main.log](https://github.com/user-attachments/files/15878797/main.log)
[crynux-server.log](https://github.com/user-attachments/files/15878815/crynux-server.log)

## Device Position

**At home 
---

## Operating System

Windows 

## How do you Start the Crynux Node

**Method:**
-  binary release

error image 
![image](https://github.com/crynux-ai/crynux-node/assets/69171259/daea0889-b172-4392-a315-d3aed45b2ce9)

**Comment by lukewwww** [comment]
This error occurs when the Rollapp is down. The node will recover automatically when the Rollapp is back. Please monitor the status of the Rollapp in the tech-headsup channel of the Discord server
