### ISSUE TITLE
Properly display card model and VRAM in the netstats monitor

### ISSUE THREAD

**Issue by lukewwww** [crynux-ai/crynux-node#89]
We don't record the card model and VRAM size in the last version, so all the cards are displayed as 4090 in the netstats monitor right now.

The APIs to get network stats are implemented in the Relay right now. The API and the web UI should be updated to properly display the card model and VRAM size.

**Comment by iwehf** [comment]
Fixed in pr https://github.com/crynux-ai/crynux-relay/pull/12
